from django.contrib import admin, messages
from django.utils import timezone
from django.utils.html import format_html, format_html_join, linebreaks

from ai_tools import services as ai_services
from .models import Category, Product, BlogPost, QuoteRequest, Order


@admin.register(Category)
class CategoryAdmin(admin.ModelAdmin):
    list_display = ["name", "parent", "display_order", "slug"]
    fields = ["name", "slug", "parent", "display_order", "image", "image_alt",
              "description", "meta_title", "meta_description"]
    list_filter = ["parent"]
    list_editable = ["display_order"]
    prepopulated_fields = {"slug": ["name"]}


@admin.register(Product)
class ProductAdmin(admin.ModelAdmin):
    list_display = ["name", "category", "grade", "purity", "seo_score",
                    "structured_state", "stock_status", "featured"]
    list_filter = ["category", "grade", "is_small_pack", "stock_status", "featured"]
    search_fields = ["name", "cas_number", "synonyms"]
    prepopulated_fields = {"slug": ["name"]}
    readonly_fields = ["ai_draft_preview", "content_quality_report", "seo_score",
                       "content_generated_at"]
    actions = ["generate_ai_draft", "generate_structured_content", "suggest_internal_links_action"]
    fieldsets = [
        (None, {"fields": ["category", "name", "slug", "image", "image_alt"]}),
        ("Specifications", {
            "fields": ["cas_number", "synonyms", "grade", "purity", "chemical_formula",
                       "molecular_weight", "appearance", "packaging"],
            "description": "Leave a field blank rather than estimating it — blank shows "
                           "as “Requires manual verification” to staff and is simply "
                           "omitted from the public page.",
        }),
        ("Safety & transport classification — never AI-generated", {
            "fields": ["un_number", "signal_word", "hazard_class", "hazard_statements"],
            "description": "Signal word (Danger/Warning), GHS hazard class "
                           "(e.g. Skin corrosion/irritation) and H-code statements are "
                           "DIFFERENT things — keep them in their own fields. UN number "
                           "depends on concentration and packing group; take it from the SDS.",
        }),
        ("Content (unique per product — no templates)", {"fields": ["description", "applications", "safety_info", "faqs"]}),
        ("Structured content — editable section by section", {
            "fields": ["content_sections", "seo_assets", "image_seo", "internal_links"],
            "description": "Generated by the structured AI pipeline and editable here. "
                           "Leave empty to keep rendering this product from the flat "
                           "Content fields above.",
        }),
        ("Content quality", {"fields": ["seo_score", "content_generated_at", "content_quality_report"]}),
        ("Commerce", {
            "fields": ["is_small_pack", "price_kes", "small_pack_size", "stock_status", "featured"],
            "description": "`in_stock` is derived from Stock status on save and is not "
                           "edited directly.",
        }),
        ("SEO", {"fields": ["meta_title", "meta_description", "focus_keyword", "regions"]}),
        ("AI assist — draft only, review before saving", {"fields": ["ai_draft_preview"]}),
    ]

    @admin.display(description="Structured")
    def structured_state(self, obj):
        """At-a-glance: does this product use structured sections, and does it
        still carry unverified specs?"""
        if not obj.has_structured_content:
            return "flat"
        pending = obj.pending_verification
        return f"✓ ({len(pending)} to verify)" if pending else "✓"

    @admin.display(description="Validation report")
    def content_quality_report(self, obj):
        report = obj.content_report or {}
        if not report:
            return "No structured content generated yet."
        issues = report.get("issues", [])
        metrics = report.get("metrics", {})
        if issues:
            issues_html = format_html_join(
                "", "<li><strong>{}</strong> — {}: {}</li>",
                ((i.get("severity", ""), i.get("field", ""), i.get("message", "")) for i in issues),
            )
        else:
            issues_html = format_html("<li>No issues found.</li>")
        return format_html(
            "<div style='max-width:720px'>"
            "<p><strong>Score:</strong> {} / 100 — <strong>{}</strong></p>"
            "<p><strong>Words:</strong> {} · <strong>FAQs:</strong> {} · "
            "<strong>Repetition:</strong> {}% · <strong>Sections:</strong> {}/{}</p>"
            "<ul>{}</ul>"
            "<p><em>The score measures on-page completeness, not ranking. "
            "Unverified specifications are a warning by design — fill them from "
            "the supplier SDS/COA rather than estimating.</em></p>"
            "</div>",
            report.get("score", 0),
            "publishable" if report.get("publishable") else "blocked — resolve the errors below",
            metrics.get("word_count", 0), metrics.get("faq_count", 0),
            round(metrics.get("repetition_ratio", 0) * 100),
            metrics.get("sections_present", 0), metrics.get("sections_required", 0),
            issues_html,
        )

    @admin.display(description="AI draft preview")
    def ai_draft_preview(self, obj):
        draft = obj.ai_draft or {}
        if not draft:
            return "No AI draft yet — select this product in the list view and run the " \
                   "“Generate AI content draft” action."
        faqs_html = format_html_join(
            "", "<li><strong>{}</strong><br>{}</li>",
            ((f.get("q", ""), f.get("a", "")) for f in draft.get("faqs", [])),
        )
        return format_html(
            "<div style='max-width:640px'>"
            "<p><strong>Meta title</strong> ({} chars): {}</p>"
            "<p><strong>Meta description</strong> ({} chars): {}</p>"
            "<p><strong>Description:</strong>{}</p>"
            "<p><strong>Applications:</strong>{}</p>"
            "<p><strong>Safety info:</strong>{}</p>"
            "<p><strong>Image alt:</strong> {}</p>"
            "<p><strong>FAQs:</strong></p><ul>{}</ul>"
            "<p><em>Generated {}. Draft only — copy what you want into the fields above, then Save.</em></p>"
            "</div>",
            len(draft.get("meta_title", "")), draft.get("meta_title", ""),
            len(draft.get("meta_description", "")), draft.get("meta_description", ""),
            linebreaks(draft.get("description", "")),
            linebreaks(draft.get("applications", "")),
            linebreaks(draft.get("safety_info", "")),
            draft.get("image_alt", ""),
            faqs_html or "—",
            obj.ai_draft_generated_at or "never",
        )

    @admin.action(description="Generate AI content draft (OpenAI)")
    def generate_ai_draft(self, request, queryset):
        generated = 0
        for product in queryset:
            try:
                draft = ai_services.generate_product_draft(product)
            except ai_services.AIConfigError:
                self.message_user(
                    request, "OPENAI_API_KEY is not set — add it to .env to use this feature.",
                    level=messages.ERROR,
                )
                return
            except Exception as exc:
                self.message_user(request, f"Failed to generate draft for {product.name}: {exc}", level=messages.WARNING)
                continue
            Product.objects.filter(pk=product.pk).update(ai_draft=draft, ai_draft_generated_at=timezone.now())
            generated += 1
        if generated:
            self.message_user(
                request, f"Generated AI draft for {generated} product(s). Open each product to review before publishing.",
                level=messages.SUCCESS,
            )

    @admin.action(description="Generate structured content (full SEO pipeline)")
    def generate_structured_content(self, request, queryset):
        """Runs the pipeline and stores the result on the live structured
        fields — but only for products whose content passed validation.
        Anything that failed is reported and left untouched, so a bulk run can
        never quietly publish a page with a fabricated claim."""
        applied, blocked = 0, []
        for product in queryset:
            try:
                payload = ai_services.generate_structured_product_content(product)
            except ai_services.AIConfigError:
                self.message_user(
                    request, "OPENAI_API_KEY is not set — add it to .env to use this feature.",
                    level=messages.ERROR,
                )
                return
            except Exception as exc:
                self.message_user(request, f"{product.name}: generation failed — {exc}",
                                  level=messages.WARNING)
                continue

            if not payload["report"]["publishable"]:
                errors = [i["message"] for i in payload["report"]["issues"]
                          if i["severity"] == "error"]
                blocked.append(f"{product.name} ({'; '.join(errors[:2])})")
                Product.objects.filter(pk=product.pk).update(
                    ai_draft=payload, ai_draft_generated_at=timezone.now()
                )
                continue

            product.content_sections = payload["sections"]
            product.seo_assets = payload["seo"]
            product.image_seo = payload["image_seo"]
            product.internal_links = payload["internal_links"]
            product.seo_score = payload["score"]
            product.content_report = payload["report"]
            product.content_generated_at = timezone.now()
            product.save()
            applied += 1

        if applied:
            self.message_user(
                request, f"Structured content published for {applied} product(s).",
                level=messages.SUCCESS,
            )
        if blocked:
            self.message_user(
                request,
                f"Held back as drafts (validation failed): {'; '.join(blocked)}. "
                "Open each product to review the report.",
                level=messages.WARNING,
            )

    @admin.action(description="Suggest internal links")
    def suggest_internal_links_action(self, request, queryset):
        for product in queryset:
            suggestions = ai_services.suggest_internal_links(product)
            if suggestions:
                text = "; ".join(f"{s['title']} ({s['type']})" for s in suggestions)
                self.message_user(request, f"{product.name}: {text}", level=messages.INFO)
            else:
                self.message_user(request, f"{product.name}: no related content found.", level=messages.INFO)


@admin.register(BlogPost)
class BlogPostAdmin(admin.ModelAdmin):
    list_display = ["title", "published", "published_at", "updated_at"]
    list_filter = ["published"]
    search_fields = ["title", "excerpt", "body"]
    prepopulated_fields = {"slug": ["title"]}
    filter_horizontal = ["related_products"]
    fieldsets = [
        (None, {"fields": ["title", "slug", "excerpt", "body", "cover_image", "cover_image_alt"]}),
        ("Internal linking", {"fields": ["related_products"]}),
        ("SEO", {"fields": ["meta_title", "meta_description"]}),
        ("Publishing", {"fields": ["published", "published_at"]}),
    ]


@admin.register(QuoteRequest)
class QuoteRequestAdmin(admin.ModelAdmin):
    list_display = ["name", "product", "quantity", "country", "created_at", "handled"]
    list_filter = ["handled", "country"]
    list_editable = ["handled"]


@admin.register(Order)
class OrderAdmin(admin.ModelAdmin):
    list_display = ["product", "customer_name", "amount_kes", "status", "created_at"]
    list_filter = ["status"]
