# Generated by Django 5.2.16 on 2026-07-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('cas_number', models.CharField(blank=True, max_length=30)),
                ('synonyms', models.CharField(blank=True, max_length=300)),
                ('grade', models.CharField(choices=[('industrial', 'Industrial / Technical'), ('food', 'Food Grade'), ('lab', 'Laboratory / Analytical'), ('pharma', 'Pharmaceutical'), ('cosmetic', 'Cosmetic Grade')], default='industrial', max_length=20)),
                ('purity', models.CharField(blank=True, help_text='e.g. ≥98%', max_length=60)),
                ('appearance', models.CharField(blank=True, max_length=200)),
                ('packaging', models.CharField(blank=True, help_text='e.g. 25 kg bags, 200 L drums', max_length=200)),
                ('description', models.TextField(help_text='Unique, human-written. 250+ words.')),
                ('applications', models.TextField(blank=True, help_text='One application per line.')),
                ('safety_info', models.TextField(blank=True)),
                ('faqs', models.JSONField(blank=True, default=list, help_text='[{"q": "...", "a": "..."}] — rendered as FAQPage schema')),
                ('is_small_pack', models.BooleanField(default=False, help_text='If true: Buy Now + M-Pesa. Else: quote only.')),
                ('price_kes', models.DecimalField(blank=True, decimal_places=2, help_text='Small-pack retail price. Leave blank for quote-only.', max_digits=12, null=True)),
                ('small_pack_size', models.CharField(blank=True, help_text='e.g. 5 L, 1 kg', max_length=60)),
                ('in_stock', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show in homepage featured section.')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('regions', models.CharField(default='Kenya, Uganda, Tanzania, Rwanda', help_text='Comma-separated, used in title/schema areaServed', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_alt', models.CharField(blank=True, max_length=160)),
                ('ai_draft', models.JSONField(blank=True, default=dict)),
                ('ai_draft_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_name', models.CharField(max_length=120)),
                ('phone', models.CharField(help_text='M-Pesa number, 2547XXXXXXXX', max_length=30)),
                ('delivery_address', models.TextField()),
                ('mpesa_checkout_id', models.CharField(blank=True, max_length=100)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.CharField(help_text='Shown in list view and used as meta_description fallback.', max_length=300)),
                ('body', models.TextField(help_text='Markdown. Rendered server-side on the frontend.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('cover_image_alt', models.CharField(blank=True, max_length=160)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_products', models.ManyToManyField(blank=True, related_name='related_posts', to='catalog.product')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('quantity', models.CharField(help_text='e.g. 10 x 25kg bags', max_length=120)),
                ('country', models.CharField(default='Kenya', max_length=60)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, help_text='Optional — blank for general inquiries not tied to one product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
