# Generated by Django 5.2.16 on 2026-07-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_ai_draft_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text="Primary search phrase this product should rank for, e.g. 'caustic soda flakes kenya' — drives the on-page SEO checklist in the admin control center.", max_length=100),
        ),
    ]
