# Generated by Django 5.2.16 on 2026-07-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Tile/banner image for this category. Landscape (approx 4:3) works best.', null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Describes the image for search engines and screen readers.', max_length=160),
        ),
    ]
