# Generated by Django 5.2.16 on 2026-07-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_image_category_image_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mpesa_checkout_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mpesa_receipt',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='Contact number, e.g. 2547XXXXXXXX', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_small_pack',
            field=models.BooleanField(default=False, help_text='Sold in small-pack sizes. All products are quote-only.'),
        ),
    ]
