# Generated by Django 5.2.16 on 2026-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_order_mpesa_checkout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_report',
            field=models.JSONField(blank=True, default=dict, help_text='Validation issues and metrics from the last generation.'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_sections',
            field=models.JSONField(blank=True, default=dict, help_text='Structured page sections (summary, features, benefits, specs, industries, FAQs…). Empty means this product renders from the flat description fields above.'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_seo',
            field=models.JSONField(blank=True, default=dict, help_text='Image alt, title, caption and suggested file name.'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_links',
            field=models.JSONField(blank=True, default=list, help_text='Suggested internal links, resolved against real routes only.'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_assets',
            field=models.JSONField(blank=True, default=dict, help_text='Keyword groups, heading outline, canonical path, Open Graph and Twitter metadata.'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
