# Generated by Django 5.2.16 on 2026-07-30 11:51

from django.db import migrations, models


def seed_stock_status(apps, schema_editor):
    """Carry the existing boolean into the new four-state field.

    Without this every product would land on the "in_stock" default, and
    Product.save() now derives `in_stock` FROM `stock_status` — so the first
    save of a genuinely out-of-stock product would silently flip it back to
    in stock. Today all 178 rows are in stock, so this is a no-op on the
    current data; it exists so the migration is correct on any database.
    """
    Product = apps.get_model("catalog", "Product")
    Product.objects.filter(in_stock=False).update(stock_status="out_of_stock")
    Product.objects.filter(in_stock=True).update(stock_status="in_stock")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_content_generated_at_product_content_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chemical_formula',
            field=models.CharField(blank=True, help_text='e.g. H2SO4. Leave blank if unverified.', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='hazard_class',
            field=models.CharField(blank=True, help_text='e.g. Class 8 (Corrosive). Read it off the SDS, never estimate.', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='molecular_weight',
            field=models.CharField(blank=True, help_text='e.g. 98.08 g/mol. Leave blank if unverified.', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('low_stock', 'Low stock'), ('on_request', 'Available on request'), ('out_of_stock', 'Out of stock')], default='in_stock', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='un_number',
            field=models.CharField(blank=True, help_text='e.g. UN1830. Transport classification — read it off the SDS, never estimate.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Derived from Stock status on save — edit that field instead.'),
        ),
        migrations.RunPython(seed_stock_status, migrations.RunPython.noop),
    ]
