# Generated by Django 5.2.16 on 2026-07-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_chemical_formula_product_hazard_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='identifier_source',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
