# Generated by Django 5.2.16 on 2026-07-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_identifier_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.CharField(blank=True, help_text='e.g. 1.83 g/cm³. For solutions this varies with concentration — check it matches the grade you actually supply.', max_length=60),
        ),
    ]
