# Generated by Django 5.2.16 on 2026-07-30 13:05

from django.db import migrations, models


def clear_conflated_hazard_class(apps, schema_editor):
    """Wipe the malformed values written by the first backfill.

    That pass stored "Danger — H314: Causes severe skin burns and eye damage"
    into `hazard_class`, which packs a signal word, a hazard statement and no
    hazard class at all into one field. Those 91 rows cannot be salvaged in
    place — they are cleared so `backfill_identifiers` can repopulate the three
    fields correctly. Anything a human typed is left alone: only values
    matching the machine-written shape are removed.
    """
    Product = apps.get_model("catalog", "Product")
    Product.objects.filter(hazard_class__regex=r"^(Danger|Warning)\s+—\s+H\d{3}").update(
        hazard_class="")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_density'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hazard_statements',
            field=models.JSONField(blank=True, default=list, help_text='H-codes with their text, e.g. ["H314: Causes severe skin burns and eye damage"].'),
        ),
        migrations.AddField(
            model_name='product',
            name='signal_word',
            field=models.CharField(blank=True, help_text='GHS signal word — "Danger" or "Warning".', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='hazard_class',
            field=models.CharField(blank=True, help_text='GHS hazard class, e.g. Skin corrosion/irritation. NOT the signal word and NOT an H-code — those are separate fields above.', max_length=120),
        ),
        migrations.RunPython(clear_conflated_hazard_class, migrations.RunPython.noop),
    ]
