# Generated by Django 5.2.16 on 2026-07-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_ghs_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Finished'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='running', max_length=12)),
                ('scope', models.CharField(blank=True, max_length=200)),
                ('product_ids', models.JSONField(blank=True, default=list)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('published', models.PositiveIntegerField(default=0)),
                ('held', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('results', models.JSONField(blank=True, default=list)),
                ('detail', models.TextField(blank=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
